version: '3.7'

services:
  server:
    # platform: linux/amd64
    build: ./
    ports:
      - '8808:8808'
    volumes:
      - /app/node_modules
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres-data-gradeviser-server:
